//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCS.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is now available on the RCS platform to advertise all the services it provides (direct advertisement to promote a restaurant or cafe - sale of the restaurant or café - job advertisement) for free for a very limited period Advertising prices will be announced on the site later..
        /// </summary>
        public static string abContent {
            get {
                return ResourceManager.GetString("abContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountants.
        /// </summary>
        public static string Accountants {
            get {
                return ResourceManager.GetString("Accountants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: 22 Manchiet el tairan st.khalifa el maamoun . heliopolis.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address :.
        /// </summary>
        public static string addressText {
            get {
                return ResourceManager.GetString("addressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertises.
        /// </summary>
        public static string Advertises {
            get {
                return ResourceManager.GetString("Advertises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string advName {
            get {
                return ResourceManager.GetString("advName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Advertises.
        /// </summary>
        public static string AllAdvertises {
            get {
                return ResourceManager.GetString("AllAdvertises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annoucements.
        /// </summary>
        public static string Annoucements {
            get {
                return ResourceManager.GetString("Annoucements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        public static string Announcements {
            get {
                return ResourceManager.GetString("Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        public static string Basis {
            get {
                return ResourceManager.GetString("Basis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy / Sell.
        /// </summary>
        public static string BuySell {
            get {
                return ResourceManager.GetString("BuySell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafe Processing.
        /// </summary>
        public static string CafeProcessing {
            get {
                return ResourceManager.GetString("CafeProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password .
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiefs.
        /// </summary>
        public static string Chiefs {
            get {
                return ResourceManager.GetString("Chiefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaners.
        /// </summary>
        public static string Cleaners {
            get {
                return ResourceManager.GetString("Cleaners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string Confirmnewpassword {
            get {
                return ResourceManager.GetString("Confirmnewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirmpassword {
            get {
                return ResourceManager.GetString("Confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An electronic platform that serves everyone who works in the field of cafes, restaurants and the food and beverage industry in general, whether you are a project owner or preparing to open a new project or even looking for a new job in a field related to the food and beverage industry, all this and more are available to us at RCS.
        /// </summary>
        public static string content1 {
            get {
                return ResourceManager.GetString("content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is unique about us is that we are the first to find a platform specialized in serving restaurants and cafes in order to save time for the seller and buyer Join our RCS platforms and benefit from the excellent site services. Offer your services
        ///        that you need or the need that you sell or provide.
        /// </summary>
        public static string content2 {
            get {
                return ResourceManager.GetString("content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your own ad for a limited time on the RCS platform. Create an unlimited number of your ads on the platform, all this and more, with promotional privileges beyond imagination..
        /// </summary>
        public static string content3 {
            get {
                return ResourceManager.GetString("content3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Brandings.
        /// </summary>
        public static string CreateBrandings {
            get {
                return ResourceManager.GetString("CreateBrandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creativity.
        /// </summary>
        public static string creativity {
            get {
                return ResourceManager.GetString("creativity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Currentpassword {
            get {
                return ResourceManager.GetString("Currentpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        public static string DateAdded {
            get {
                return ResourceManager.GetString("DateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design and Print Menus.
        /// </summary>
        public static string DesignandPrintMenus {
            get {
                return ResourceManager.GetString("DesignandPrintMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGP.
        /// </summary>
        public static string EGP {
            get {
                return ResourceManager.GetString("EGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: artmedia2017.eg@gmail.com.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email :.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Field Required ..
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Address.
        /// </summary>
        public static string errorAddress {
            get {
                return ResourceManager.GetString("errorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Confrim Password.
        /// </summary>
        public static string errorConPass {
            get {
                return ResourceManager.GetString("errorConPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Email.
        /// </summary>
        public static string errorEmail {
            get {
                return ResourceManager.GetString("errorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Gender.
        /// </summary>
        public static string errorGender {
            get {
                return ResourceManager.GetString("errorGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password.
        /// </summary>
        public static string errorPass {
            get {
                return ResourceManager.GetString("errorPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Phone Number.
        /// </summary>
        public static string errorPhon {
            get {
                return ResourceManager.GetString("errorPhon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter UserName.
        /// </summary>
        public static string errorUserName {
            get {
                return ResourceManager.GetString("errorUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior Design.
        /// </summary>
        public static string ExteriorDesign {
            get {
                return ResourceManager.GetString("ExteriorDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franchise Guide.
        /// </summary>
        public static string FranchiseGuide {
            get {
                return ResourceManager.GetString("FranchiseGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender :.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Select All Images For This Item ..
        /// </summary>
        public static string imagesInq {
            get {
                return ResourceManager.GetString("imagesInq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individuation.
        /// </summary>
        public static string individ {
            get {
                return ResourceManager.GetString("individ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interior Design.
        /// </summary>
        public static string InteriorDesign {
            get {
                return ResourceManager.GetString("InteriorDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can offer to buy or sell the restaurant or the cafe.
        /// </summary>
        public static string l1 {
            get {
                return ResourceManager.GetString("l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase of all equipment and supplies for preparing the restaurant or the cafe.
        /// </summary>
        public static string l2 {
            get {
                return ResourceManager.GetString("l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for jobs related to managing restaurant or cafe projects.
        /// </summary>
        public static string l3 {
            get {
                return ResourceManager.GetString("l3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LandLine: (+20) 26905208.
        /// </summary>
        public static string lnd {
            get {
                return ResourceManager.GetString("lnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Request.
        /// </summary>
        public static string Make_Request {
            get {
                return ResourceManager.GetString("Make Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Make Advertise.
        /// </summary>
        public static string MakeAdvertise {
            get {
                return ResourceManager.GetString("MakeAdvertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make An Advertise.
        /// </summary>
        public static string MakeAnAdvertise {
            get {
                return ResourceManager.GetString("MakeAnAdvertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Request.
        /// </summary>
        public static string MakeRequest {
            get {
                return ResourceManager.GetString("MakeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers.
        /// </summary>
        public static string Managers {
            get {
                return ResourceManager.GetString("Managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages :.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile: (+20) 1020689999 /  1028666161.
        /// </summary>
        public static string mob {
            get {
                return ResourceManager.GetString("mob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Advertises.
        /// </summary>
        public static string MyAdvertises {
            get {
                return ResourceManager.GetString("MyAdvertises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Annoucements.
        /// </summary>
        public static string MyAnnoucements {
            get {
                return ResourceManager.GetString("MyAnnoucements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Newpassword {
            get {
                return ResourceManager.GetString("Newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News / Events.
        /// </summary>
        public static string NewsEvents {
            get {
                return ResourceManager.GetString("NewsEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Advertises Found !!.
        /// </summary>
        public static string noAdvertise {
            get {
                return ResourceManager.GetString("noAdvertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertise Deleted !!.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string OwnerEmail {
            get {
                return ResourceManager.GetString("OwnerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Info.
        /// </summary>
        public static string OwnerInfo {
            get {
                return ResourceManager.GetString("OwnerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string OwnerPhone {
            get {
                return ResourceManager.GetString("OwnerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first electronic RCS platform through which we provide all restaurant and café owners with all restaurant or cafe services.
        /// </summary>
        public static string parag {
            get {
                return ResourceManager.GetString("parag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password : .
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.....
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone :.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Address.
        /// </summary>
        public static string ProductAddress {
            get {
                return ResourceManager.GetString("ProductAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Info.
        /// </summary>
        public static string ProductInfo {
            get {
                return ResourceManager.GetString("ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Price.
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want delete this advertise ?.
        /// </summary>
        public static string prompt {
            get {
                return ResourceManager.GetString("prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me ? .
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        public static string Renew {
            get {
                return ResourceManager.GetString("Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants Processing.
        /// </summary>
        public static string RestaurantsProcessing {
            get {
                return ResourceManager.GetString("RestaurantsProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shops.
        /// </summary>
        public static string Shops {
            get {
                return ResourceManager.GetString("Shops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specializing.
        /// </summary>
        public static string special {
            get {
                return ResourceManager.GetString("special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Work.
        /// </summary>
        public static string SpecialWork {
            get {
                return ResourceManager.GetString("SpecialWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stewarts.
        /// </summary>
        public static string Stewarts {
            get {
                return ResourceManager.GetString("Stewarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-left.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resturant and Cafe Service.
        /// </summary>
        public static string TitleQoute {
            get {
                return ResourceManager.GetString("TitleQoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Request.
        /// </summary>
        public static string UpdateRequest {
            get {
                return ResourceManager.GetString("UpdateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Images.
        /// </summary>
        public static string UploadImages {
            get {
                return ResourceManager.GetString("UploadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName :.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We help you in promoting the restaurant or café locally and internationally, So here you will be in the hands of all those you are looking for, whether potential clients, project owners or job seekers..
        /// </summary>
        public static string whCon {
            get {
                return ResourceManager.GetString("whCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who We Are ?.
        /// </summary>
        public static string WhoWeAre {
            get {
                return ResourceManager.GetString("WhoWeAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message :.
        /// </summary>
        public static string Yourmessage {
            get {
                return ResourceManager.GetString("Yourmessage", resourceCulture);
            }
        }
    }
}
