// <auto-generated />
namespace RCS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202010102139391_createTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
